spring.application.name=apiEnergy

spring.datasource.url=${DB_Url}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

jwt.secret=VGhpcy1pcy1qdXN0LWEtZHVtbXktc2VjcmV0LWtleS1mb3ItdGVzdGluZw==
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
