apiVersion: v1
kind: Service

metadata:
  name: energy-service
  namespace: energy

spec:
  type: NodePort

  selector:
    app: energy-api

  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30007